version: '3'
services:
    mongodb:
        image: mongo:4.2
        container_name: mongodb-text-search
        ports:
            - '27017:27017'
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: root
        networks: 
            - support-net
        
    mongo-express:
        image: mongo-express
        container_name: mongo-express-text-search
        restart: always
        ports:
            - '8082:8082'
        depends_on:
            - mongodb
        environment:
            ME_CONFIG_MONGODB_URL: 'mongodb://root:root@mongodb:27017'
            ME_CONFIG_MONGODB_AUTH_USERNAME: root
            ME_CONFIG_MONGODB_AUTH_PASSWORD: root
            VCAP_APP_PORT: 8082
        networks: 
            - support-net    

networks:
  support-net:
    driver: bridge
    
volumes:
    mongodb-data:
        driver: local
